server:
  port: 8080

spring.application.name: EUREKA_SERVER

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
  serviceUrl:
          defaultZone: http://localhost:8080/eureka/